---
- name: Set linter failure to false
  set_fact:
    linter_failure: false

- name: Run Coala
  command: coala --ci
  args:
    chdir: "{{ zuul.project.src_dir }}"
  register: _coala
  ignore_errors: yes

- name: Set linter failure to true if Coala failed
  set_fact:
    linter_failure: true
  when: _coala.rc

- name: Fail if linter failed
  fail:
    msg: "Coala linter failed checks"
  when: linter_failure