---
- name: "Run coala"
  shell: scl enable rh-python36 coala --non-interactive
  register: _coala
  ignore_errors: yes
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ ansible_env.HOME }}/.local/bin"
  args:
    chdir: "{{ zuul.project.src_dir }}"

- name: Set linter failure to true
  set_fact:
    linter_failure: true
  when: _coala.rc
