---
- name: "Run coala"
  shell: coala --config .coafile --non-interactive
  register: _coala
  ignore_errors: yes
  environment:
    LC_ALL: "C"
    PATH: "/opt/rh/rh-python36/root/usr/bin:{{ ansible_env.PATH }}:{{ ansible_env.HOME }}/.local/bin"
    LD_LIBRARY_PATH: "/opt/rh/rh-python36/root/usr/lib64:{{ ansible_env.LD_LIBRARY_PATH }}"
    PKG_CONFIG_PATH: "/opt/rh/rh-python36/root/usr/lib64/pkgconfig:{{ ansible_env.PKG_CONFIG_PATH }}"
    XDG_DATA_DIRS: "/opt/rh/rh-python36/root/usr/share:{{ ansible_env.XDG_DATA_DIRS }}:/usr/local/share:/usr/share"

  args:
    chdir: "{{ zuul.project.src_dir }}"

- name: Set linter failure to true
  set_fact:
    linter_failure: true
  when: _coala.rc