---
- hosts: all

  tasks:
    - name: Trigger OpenShift Build
      uri:
        method: POST
        url: "{{ webhook_url }}"
        validate_certs: no
        follow_redirects: all
        headers:
          Content-Type: "application/json"
