---
- name: Check to see if the Pipfile exists
  stat:
    path: Pipfile
    get_checksum: false
    get_mime: false
    get_md5: false
  register: stat_results

#- name: Fail if Pipfile file is missing
#  when: not stat_results.stat.exists
#  fail:
#    msg: Pipfile was not found

- name: Pipenv install
  args:
    chdir: "{{ zuul_work_dir }}"
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ ansible_env.HOME }}/.local/bin"
  command: "{{ pipenv_executable }} install --deploy"

- name: Run Pipenv
  args:
    chdir: "{{ zuul_work_dir }}"
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ ansible_env.HOME }}/.local/bin"
  command: "{{ pipenv_executable }} run {{ pipenv_extra_args }}"
